name: Deploy
on:
  workflow_run:
    workflows: ["Build"]
    branches: ["main"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get build result from cache
      id: cache
      uses: actions/cache@v4.1.1
      with:
        path: public/
        key: ${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ github.ref }}
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      if: steps.cache.outputs.cache-hit == 'true'
      with:
        branch: gh-pages
        folder: public
        clean: true
        single-commit: true
        commit-message: 'chore: deploy to Github Pages from ${{ github.sha }}'
