name: Build and Deploy

on:
  schedule:
    - cron:  '0 */24 * * *'
  workflow_dispatch:
    inputs:
      ignore-dep-cache:
        description: Ignore dependencies cache (`true` to enable)
        default: 'false'
  push:

jobs:

  cancel-previous:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Look up dependencies in cache
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules/
        key: ${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: ${{ 'true' == github.event.inputs.ignore-dep-cache || 'true' != steps.cache.outputs.cache-hit }}
      run: npm ci

  build:
    name: Build
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS   
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Look up dependencies in cache
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules/
        key: ${{ hashFiles('package-lock.json') }}
    - name: Build
      run: npm run build
      env:
        PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
        GRAPHQL_URL: https://api.github.com/graphql
        GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: public

  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: public
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: public
        clean: true
        single-commit: true
        commit-message: 'chore: deploy to Github Pages from ${{ github.sha }}'
