name: Build and Deploy Gatsby four times a day

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS   
      uses: actions/setup-node@v1
    - name: Look up dependencies in cache
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules/
        key: ${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build
    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --dir=public --prod
        secrets: '[ "NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID" ]'